### ISSUE TITLE
Does it only work on bash?

### ISSUE THREAD

**Issue by aasutossh** [Traap/nvims#10]
I am using zsh and running `nvims` result in following:
```
❯ nvims
not a valid number: ~50
Nothing selected
```

**Comment by Traap** [comment]
@aasutossh I just started using zsh and nvims is working.  Do you have fzf installed?  What operating system are you using?

**Comment by aasutossh** [comment]
I am using [archcraft](https://archcraft.io) based on arch linux.
I'll try once more and report back.

**Comment by aasutossh** [comment]
Working perfectly my bad earlier.

**Comment by Traap** [comment]
@aasutossh  - I do have it working in zsh.  Also, I  suspect the bash script is 100% posix compliant.
