### ISSUE TITLE
nvchad not launching

### ISSUE THREAD

**Issue by Paulobox** [Traap/nvims#11]
hi, when I launch nvchad from nvims it just opens default nvim

**Comment by Traap** [comment]
@Paulobox 
I confirmed your findings.  NvChad does not providing init.lua file.    You can also confirm my findings reviewing ~/.config/nvim-chad which is the location on Linux computers nvims clones repositories into.

Any additional information you can provide would be helpful.

**Comment by Traap** [comment]
@Paulobox 
NvChad is now working.  nvims testing was confirmed using https://nvchad.com/docs/quickstart/install/ instruction.

**Comment by Traap** [comment]
@Paulobox  Thank you for reporting the issue.

**Comment by Paulobox** [comment]
okey it works now.Maybe I was just having problem in arch linux. but I removed cached folders and now it works.

Thanks for this script , it really helps to test different Nvim configs!

**Comment by Paulobox** [comment]
@Traap 

okey it works now.Maybe I was just having problem in arch linux. but I removed cached folders and now it works.

Thanks for this script , it really helps to test different Nvim configs!
