### ISSUE TITLE
Add default nvim configuration

### ISSUE THREAD

**Issue by MustCodeAl** [Traap/nvims#12]
Adding a default nvim configuration so the menu doesn't have to be used every time would make using this manager much more smoother

**Comment by Traap** [comment]
Interesting idea.  How would you allow a person to set the default configuration?

**Comment by MustCodeAl** [comment]
> Interesting idea. How would you allow a person to set the default configuration?

so I made a [modification](https://github.com/Traap/nvims/compare/master...MustCodeAl:nvims:nvimdefault) to use `nvims set-default` but I didn't test it yet

**Comment by Traap** [comment]
Nice approach.  Test it.  Make a PR when you are ready.

**Comment by Traap** [comment]
Nice work.  Thank you for the PR.
