### ISSUE TITLE
Hey Thank you

### ISSUE THREAD

**Issue by mbaneshi** [Traap/nvims#3]
It is not clear what should we do to activate it. I run the bash script.  

Now `~/.config/nvims/exists and it has 2 files;

.rw-r--r-- 1.2k mac 20 Dec 14:01  neovim_distros
.rw-r--r--   35 mac 20 Dec 14:08  nvim_appnames

So what is the next?

**Comment by pwnwriter** [comment]
run **`nvims`**  in your terminal. Select which distro to run and press enter :)

**Comment by Traap** [comment]
@pwnwriter is correct.  

Check out this video:  https://www.youtube.com/watch?v=xyJX55Zf99k&t=6s

Keep the following in mind:
1. install nvims
2. After nvims, should be in  your path, so run nvims, if not you need to adjust your path.
3. Select the distro.  It will bootstrap itself.
4. After  installing a distro, you need a new shell that has sourced ~/.config/nvims/nvim_appnames
5. nvim-traap should now work.

**Comment by mbaneshi** [comment]
I ran , nvims is on my path and executed fairly,  but there is nothing to
choose , my options is empty,  I wonder whether,  Myself should clone those
nice repos , or it would do automatically,  and how I should feed my
opinion list? Thanks in advance

**Comment by pwnwriter** [comment]
Do you have fzf installed or not? 

> Nothing to choose

Please show screenshot.

**Comment by mbaneshi** [comment]
yes ,i have fzf in path .
my original configure is lazyvim 
<img width="1440" alt="Screen Shot 2023-12-20 at 20 11 29" src="https://github.com/Traap/nvims/assets/21130612/7d2407c7-e33a-42dc-917a-71247f55b1b3">
<img width="1440" alt="Screen Shot 2023-12-20 at 20 11 49" src="https://github.com/Traap/nvims/assets/21130612/51e1e016-4335-40ac-826e-3aa59441dc3a">

**Comment by mbaneshi** [comment]
<img width="1440" alt="Screen Shot 2023-12-20 at 20 17 01" src="https://github.com/Traap/nvims/assets/21130612/d2e987ec-9c12-4c89-bab8-7c6d5c50fa2e">


This is my original nvim ,

**Comment by pwnwriter** [comment]
What's up with your neovim_distros file?
Do cat

```bash
cat ~/.config/nvims/neovim_distros
```

**Comment by pwnwriter** [comment]
if the file doesn't have any content put contents from the repos `neovim_distros` file. 

AFAIK, traap haven't used anything that does care for specifically Linux. It should work around unix. The piping and all the stuffs.

**Comment by mbaneshi** [comment]
@Traap 
@pwnwriter 

```bash

cat ~/.config/nvims/neovim_distros                                                                                                                                      took 6s   22:37 ❯ 
#!/bin/bash
# Define Neovim applications you want to experiment with.

# The repository cloned must bootstrap itself.  In otherwords, clone and nvim
# is all tha tis needed.
#
# alias      | Github repository       | default or branch name
readonly neovim_distros=(
  "astro     | AstroNvim/AstroNvim     | default"
  "asyncedd  | asyncedd/dots.nvim      | default"
  "barebones | Traap/barebones         | default"
  "baretmux  | Traap/barebones         | tmux"
  "default   | none                    | none"
  "exos      | exosyphon/nvim          | none"
  "kickstart | nvim-lua/kickstart.nvim | default"
  "lervag    | lervag/dotnvim          | default"
  "nvchad    | NvChad/NvChad           | default"
  "nvconf    | TechnicalDC/NvConf      | default"
  "prime     | Traap/init.lua          | default"
  "starter   | LazyVim/starter         | default"
  "traap     | Traap/nvim              | default"
  "vapour    | Traap/VapourNvim        | default"
  "void      | nvoid-lua/nvoid         | default"
  "xray      | Traap/nvim              | v0.9.5-lazyvim"
  "zero      | Traap/lazy.zero         | default"
  "zulu      | Traap/nvim              | v0.6.8-packer"
  "OVIwrite  | MiragianCycle/OVIWrite  | default"
)

```

**Comment by Traap** [comment]
@mbaneshi  I do not have a MacOSX machine.  We might be running into difference in bash interperters.


### Code change for debugging
![image](https://github.com/Traap/nvims/assets/1930415/8bda708c-7339-4565-801c-29909e08294b)

### Sample Output
![image](https://github.com/Traap/nvims/assets/1930415/762a8951-5b43-4080-aff1-80d173b48601)

Post an image.

**Comment by mbaneshi** [comment]
yes , alias output not works , my default Shell is fish , I clone repo with git clone , and did the rest , and also change mentioned line for debug , at the end there is no output.
I did same for bash , yet no out put .



```bash
bash-5.2$ bash --version
GNU bash, version 5.2.21(1)-release (x86_64-apple-darwin20.6.0)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by Traap** [comment]
Interesting.  I'm not sure how to help you get bash setup on the max.  I did check the code for any non-standard compatibility issues with GNU Bash and found nothing.  I did updated line 1 to use the system default interpreter for bash.

```bash
#!/usr/bin/env bash
```

I do not expect this to correct your issue.

**Comment by mbaneshi** [comment]
@Traap Thank you for time, and effort. ❤️
