### ISSUE TITLE
Empty selection

### ISSUE THREAD

**Issue by mikaoelitiana** [Traap/nvims#6]
I have just installed nvims on MacOs but the distro list is empty 

<img width="1718" alt="image" src="https://github.com/Traap/nvims/assets/674667/33c7557d-9eb9-4d2a-86aa-fd6bb70b0c98">

**Comment by Traap** [comment]
@mikaoelitiana  What operating system are you using?  Are you using bash?   I have not tested with anything but bash.

Review #3 too.  It is the troubleshooting with did for a fish user.

**Comment by mikaoelitiana** [comment]
I am using fish, I think the solution in #3 should work then.
